[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF4433"
backgroundColor = "#120608"
secondaryBackgroundColor = "#1A0A0C"
textColor = "#FFFFFF"
font = "sans serif"
